{
 "title": "Speedtest",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Download/Upload Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(speedtest_download_speed_Bps{user_isp=\"Starlink\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "avg(speedtest_upload_speed_Bps{user_isp=\"Starlink\"})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Best Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_download_speed_Bps[1w:5m]))"
    }
   ]
  },
  {
   "title": "Worst Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_download_speed_Bps[1w:5m]))"
    }
   ]
  },
  {
   "title": "Best Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_upload_speed_Bps[1w:5m]))"
    }
   ]
  },
  {
   "title": "Worst Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_upload_speed_Bps[1w:5m]))"
    }
   ]
  },
  {
   "title": "Best Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_latency_seconds[1w:5m]))"
    }
   ]
  },
  {
   "title": "Worst Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_latency_seconds[1w:5m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(speedtest_latency_seconds{user_isp=\"Starlink\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Test Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(speedtest_scrape_duration_seconds)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "speedtest_download_speed_Bps" },
    { "expr": "speedtest_upload_speed_Bps" },
    { "expr": "speedtest_latency_seconds", "legendFormat": "Latency" }
   ]
  }
 ]
}